Server/src/server/gameCenter/models/game/Game.java, Server/src/server/gameCenter/models/game/Player.java
There is still discussion as of now on whether we want draw 2 or draw 1, but for now I went in and made a quick change to easily allow switching from one or the other.
Changes:
-Starting hand reduced from 5/5 to 3/5.
-If the player has 3/5 cards in their hand they will draw two cards at the end of their turn.
-If the player has 4/5 cards in their hand they will only draw 1 card at the end of their turn
-If the player has a full hand they will not draw any card at the end of their turn.
=> Draw two cards at the end of your turn instead of 1

.gitignore, Server/resources/accounts/john_doe.account.json, Server/resources/spellCards/Tempest.spell.card.json, resources/spellCards/Tempest.spell.card.json
Tempest: 2 Mana, Deal 2 damage to all characters.
Lightly Playtested
=> Add tempest spell

.gitignore, Server/resources/accounts/john_doe.account.json, Server/resources/spellCards/PhoenixFire.spell.card.json, resources/spellCards/PhoenixFire.spell.card.json
Add phoenix fire card to game
Lightly Playtested
=> Add phoenix fire

Server/src/server/gameCenter/models/map/GameMap.java
Deleted the three artifacts in the centre of the board (where mana springs should be)
=> Remove Artifacts In Centre of the Board

Client/src/view/BattleView/PlayerBox.java
* Removed "AI" flags from names during battle.
* Added hero portraits  (long term, this should be in Json files)
=> Hero portraits

.github/workflows/maven.yml, Server/pom.xml, Server/src/test/java/Cell_Test.java, Server/src/test/java/Example_Test.java
unit testing infrastructure setup with maven
added unit test example and started to test cell class
=> Unit testing

Client/src/view/BattleView/MapBox.java, Server/resources/accounts/duelyst.account.json, Server/resources/minionCards/MrSwampy.minion.card.json, devTools/cardCreator/cards_to_import/MrSwampy.minion.card.json, resources/minionCards/MrSwampy.minion.card.json
buffed swamp entangler (i'll explain why later)
=> Add swampy

Client/src/controller/Client.java, Client/src/models/message/Message.java, Client/src/models/message/OtherFields.java, Client/src/view/BattleView/MapBox.java
=> Add game log(basic)

Client/resources/troopAnimations/neutral_wartalon.plist.json, Server/resources/accounts/duelyst.account.json, Server/resources/minionCards/WarTalon.minion.card.json, devTools/cardCreator/cards_to_import/WarTalon.minion.card.json, resources/minionCards/WarTalon.minion.card.json
War Talon with prevoke but no frenzy.
=> War Talon (No Frenzy)

Client/resources/troopAnimations/neutral_beastswamp.plist.json
=> fixed Mr. Swampy sprite

Client/src/controller/GameController.java, Client/src/models/game/availableActions/AvailableActions.java, Server/src/server/gameCenter/models/game/availableActions/AvailableActions.java
units with 0 attack cannot attack
=> 0 attack bug fix

Client/resources/troopAnimations/neutral_mercsunseer.plist.json
=> Re-fix sun seer sprite

Client/src/controller/Client.java
Adds reconnection attempts to the client if the server does not respond properly. Just a crutch to fix some rare local client bugs. Locks the thread, which should not be an issue since the client is just starting up (and we probably want that to avoid some nasty issues coming up).
=> Add reconnects

Client/src/view/MainMenu.java, Server/src/server/GameServer.java, Server/src/server/gameCenter/GameCenter.java
=> Enabling spectate feature

Server/src/server/gameCenter/GameCenter.java, Server/src/server/gameCenter/models/game/Game.java
Instead of Threading and letting it sleep, we now use the builtin timer from java
to schedule the changeturn method (and cancel it if changeturn was called by the player's end of turn).
=> Adjusted the turn time limit logic.

.github/workflows/maven.yml, Client/pom.xml
Looks like there was a bug in the maven plugin I used that applied to the VM CI is executed in.
=> Fix java11 build

Client/src/controller/Client.java
Just some simple refactoring to make it working like a proper singleton object
=> Refactoring the client to work as a proper singleton

.github/workflows/default-project.yml
Add an action to make our only project the default. When a new issue is opened this will run and assign it to our project.
=> Default project

Server/resources/accounts/duelyst.account.json, Server/resources/minionCards/AzuriteLion.minion.card.json, Server/src/server/gameCenter/models/game/Game.java, Server/src/server/gameCenter/models/game/ServerTroop.java, devTools/cardCreator/cards_to_import/AzuriteLion.minion.card.json, resources/minionCards/AzuriteLion.minion.card.json
I'm 99% confident I got it right. You can,
- Move-Move-Attack
- Move-Attack-Move-Attack
- Move-Attack-Attack
- Attack-Move-Attack
- Attack-Attack
Hopefully there isn't any specific permutation that can break this set of sequence
=> Add celerity

Client/src/view/CollectionMenu.java
=> Fix card duplication upon search

Client/src/controller/LoginMenuController.java, Client/src/models/gui/LoginFieldsContainer.java, Client/src/models/gui/LoginMenuLogoBox.java, Client/src/models/gui/NormalPasswordField.java, Client/src/models/gui/ProfileGrid.java, Client/src/models/languageLocalisation/ButtonText.java, Client/src/models/languageLocalisation/Language.java, Client/src/models/languageLocalisation/LanguageKeys.java, Client/src/models/languageLocalisation/LoginMenu.java, Client/src/models/languageLocalisation/MainMenu.java, Client/src/models/languageLocalisation/Profile.java, Client/src/models/languageLocalisation/Spectate.java, Client/src/view/ErrorView.java, Client/src/view/LoginMenu.java, Client/src/view/MainMenu.java, Client/src/view/Show.java, Client/src/view/WaitingMenu.java, resources/configurations/Languages/brazilianPortuguese.json, resources/configurations/Languages/english.json, resources/configurations/Languages/french.json, resources/configurations/Languages/german.json, resources/configurations/Languages/korean.json, resources/configurations/Languages/russian.json, resources/configurations/Languages/spanish.json
Also makes the `json` files valid and makes some files follow naming
convention for Java.
=> Swap strings with string const in profile localisation

Client/src/main/java/org/projectcardboard/client/view/battleview/CardAnimation.java, Client/src/main/java/org/projectcardboard/client/view/battleview/HandBox.java
=> Fixed card stuttering ingame on every action

Server/resources/accounts/duelyst.account.json, Server/resources/minionCards/SpectralRevenant.minion.card.json, devTools/cardCreator/cards_to_import/SpectralRevenant.minion.card.json, resources/minionCards/SpectralRevenant.minion.card.json
* Rev now works on attack and counter attack
* Because he does 10 dmg to face, which is more than spiral, I've upped the cost to 9.
* Updated card text to better express his abilities.
* ** REQUIRES DYING WISH BRANCH.**
=> nerf + text change

Server/resources/accounts/duelyst.account.json, Server/resources/minionCards/CelestialPhantom.minion.card.json, Server/resources/minionCards/SunSeer.minion.card.json, Server/src/server/gameCenter/models/game/Game.java, devTools/cardCreator/cards_to_import/CelestialPhantom.minion.card.json, devTools/cardCreator/cards_to_import/SunSeer.minion.card.json, resources/minionCards/CelestialPhantom.minion.card.json, resources/minionCards/SunSeer.minion.card.json
on defend was broken, now works
changed some cards to work on counter
=> Fix on counterattack

Client/src/main/java/org/projectcardboard/client/view/battleview/HandBox.java
#309 
Added extra logic to update effect of slotted cards, which now properly turn grey / colourful.
=> Fixed the case in which cards would stay grey / coloured.

Client/src/main/java/org/projectcardboard/client/view/battleview/HandBox.java
=> Revert "Fixed the case in which cards would stay grey / coloured."

Client/src/main/java/org/projectcardboard/client/view/battleview/CardAnimation.java, Client/src/main/java/org/projectcardboard/client/view/battleview/HandBox.java
=> Revert "Fixed card stuttering ingame on every action"

Client/src/main/resources/troopAnimations/f3_aymarahealer.plist.json, Server/resources/accounts/duelyst.account.json, Server/resources/minionCards/AymaraHealer.minion.card.json, devTools/cardCreator/cards_to_import/AymaraHealer.minion.card.json, resources/minionCards/AymaraHealer.minion.card.json
Tested with "Fix Dying Wish" PR
=> Add Aymara Healer

Server/resources/accounts/duelyst.account.json, Server/resources/spellCards/ScionsFirstWish.spell.card.json, devTools/cardCreator/cards_to_import/ScionsFirstWish.spell.card.json, resources/spellCards/ScionsFirstWish.spell.card.json
Combined +1/+1 and draw a card in the same spell.
I can separate them if anyone wants to.
=> Add Scion's First Wish

resources/localHostConfig.txt, resources/serverConfig.txt
saving these files locally is aimed at helping us work faster
=> Local host file

Server/src/server/dataCenter/DataCenter.java
Force logout whenever a user is trying to login as someone with an active session
=> Force logout

Client/src/main/java/org/projectcardboard/client/models/gui/DeckCardsGrid.java, Client/src/main/java/org/projectcardboard/client/models/gui/DialogBox.java, Client/src/main/java/org/projectcardboard/client/models/gui/LoginFieldsContainer.java, Client/src/main/java/org/projectcardboard/client/models/gui/OrangeButton.java, Client/src/main/java/org/projectcardboard/client/view/ErrorView.java, Client/src/main/java/org/projectcardboard/client/view/GlobalChatDialog.java
Small QOL change. When someone tries to log in or register turn their cursor into a loading cursor so that they know we're waiting for a response from the server
=> Add wait cursor on log and register 

Client/src/main/java/org/projectcardboard/client/controller/SoundEffectPlayer.java, Client/src/main/java/org/projectcardboard/client/view/battleview/PlayerBox.java
Not super important, but is a nice feature for not so nice players
=> add mute button

Server/src/server/chatCenter/ChatCenter.java, Server/src/server/gameCenter/models/game/Game.java, Server/src/server/gameCenter/models/game/KillHeroBattle.java
Players (including AI) announce cards played.
Tested vs AI, needs testing on Server.  (currently broken)
=> AI now announces moves.

Client/src/main/java/org/projectcardboard/client/view/battleview/PlayerBox.java
=> Revert "Display mana in numerical form"

Server/src/server/dataCenter/DataCenter.java, Server/src/server/dataCenter/models/account/Account.java, Server/src/server/dataCenter/models/account/Collection.java
This should fix our issue of having to create new accounts whenever the server is updated with new cards. Now everyone gets to keep their favorite names
=>  update-all-user's-card-collection-when-server-has-new-cards

Client/src/main/java/org/projectcardboard/client/view/LoginMenu.java
=> Add server name to Login Screen

Server/src/server/gameCenter/models/game/Game.java, Server/src/server/gameCenter/models/game/Player.java, Shared/src/shared/models/card/Card.java
tested with AI and two clients. Does not _completely_ erase/fix the issue but makes the probability extremely low. If anyone has a better implementation in mind feel free to pitch in
=> Fix replace into same card issue

Server/resources/accounts/duelyst.account.json, Server/resources/minionCards/AymaraHealer.minion.card.json, Server/resources/spellCards/SpiralTechnique.spell.card.json, devTools/cardCreator/card_list.csv, devTools/cardCreator/cards_to_import/AymaraHealer.minion.card.json, devTools/cardCreator/cards_to_import/SpiralTechnique.spell.card.json, resources/minionCards/AymaraHealer.minion.card.json, resources/spellCards/SpiralTechnique.spell.card.json
Spiral Buff (now 7)
Aymara: now 6 mana 5/5 WITHOUT provoke
=> Balance change (spiral, aymara)

devTools/cardCreator/cards_to_import/NeedValidationChecks/FlashFreeze.spell.card.json
=> update flash freeze

.gitignore, devTools/build_exe/PackageExe.py, exported_decks/Aggro_starter_deck.deck.json, exported_decks/Golem_starter_deck.deck.json
More of a developer tool actually, given the implementation.  It allows us to quickly import playable decks when creating a new account.
=> Starterdecks

Client/src/main/java/org/projectcardboard/client/models/game/availableactions/AvailableActions.java, Server/src/server/gameCenter/models/game/Player.java, Server/src/server/gameCenter/models/game/availableActions/AvailableActions.java
Needs testing with hoppers Lock Cards
=> fix-0-cost-sufficient-mana-bug
